
<?php
## Supplimental JSON for MTGPimp

$Data = array(
		array("SetName" => "Limited Edition Alpha","Frame" => "Original", "Border" => "Black","Foil" => "No","Languages" => array("English")),
		array("SetName" => "Limited Edition Beta","Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Unlimited Edition",	"Frame" =>  "Original","Border" => "White","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Arabian Nights",	"Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Antiquities","Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Revised Edition",	"Frame" =>  "Original","Border" => "White","Foil" =>  "No","Languages" => array("English", "French", "German", "Italian")),
		array("SetName" => "Legends",	"Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English", "Italian")),
		array("SetName" => "The Dark",	"Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English", "Italian")),
		array("SetName" => "Fallen Empires",	"Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Fourth Edition",	"Frame" =>  "Original","Border" => "White","Foil" =>  "No","Languages" => array("English", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Spanish")),
		array("SetName" => "Ice Age",	 "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English", "French", "German", "Italian", "Portuguese", "Spanish")),
		array("SetName" => "Chronicles", "Frame" =>  "Original","Border" => "White","Foil" =>  "No","Languages" => array("English", "Japanese")),
		array("SetName" => "Renaissance", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("French", "German", "Italian")),
		array("SetName" => "Homelands",	 "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English", "French", "German", "Italian", "Portuguese","Spanish")),
		array("SetName" => "Alliances",	 "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English", "French", "German", "Italian", "Portuguese","Spanish")),
		array("SetName" => "Mirage",	 "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Visions",	 "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese","Spanish")),
		array("SetName" => "Fifth Edition", "Frame" =>  "Original","Border" => "White","Foil" =>  "No","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Portal",	 "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Japanese","Spanish")),
		array("SetName" => "Weatherlight", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese","Spanish")),
		array("SetName" => "Tempest",	 "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese","Spanish")),
		array("SetName" => "Stronghold", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese","Spanish")),
		array("SetName" => "Exodus",	 "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese","Spanish")),
		array("SetName" => "Portal Second Age",	"Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Urza's Saga", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese","Spanish")),
		array("SetName" => "Anthologies", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Urza's Legacy", "Frame" =>  "Original","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Classic Sixth Edition","Frame" =>  "Original","Border" => "White","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Urza's Destiny",	"Frame" =>  "Original","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Portal Three Kingdoms","Frame" =>  "Original","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "Japanese")),
		array("SetName" => "Starter 1999", "Frame" =>  "Original","Border" => "White","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Mercadian Masques",	"Frame" =>  "Original","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Nemesis",	 "Frame" =>  "Original","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Starter 2000", "Frame" =>  "Original","Border" => "White","Foil" =>  "Yes","Languages" => array("English", "French", "German", "Italian", "Japanese","Spanish")),
		array("SetName" => "Prophecy",	 "Frame" =>  "Original","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Invasion",	 "Frame" =>  "Original","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Beatdown Box Set",	"Frame" =>  "Original","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Planeshift", "Frame" =>  "Original","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Seventh Edition",	"Frame" =>  "Original","Border" => "White","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Apocalypse", "Frame" =>  "Original","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Odyssey",	 "Frame" =>  "Original","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Deckmasters", "Frame" =>  "Original","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Torment",	 "Frame" =>  "Original","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Judgment",	 "Frame" =>  "Original","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Onslaught",	 "Frame" =>  "Original","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Legions",	 "Frame" =>  "Original","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Scourge",	 "Frame" =>  "Original","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Eighth Edition",	"Frame" =>  "8th","Border" => "Black","Border" => "White","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Mirrodin",	 "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Darksteel",	 "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Fifth Dawn",	 "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Champions of Kamigawa","Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Betrayers of Kamigawa","Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Saviors of Kamigawa","Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese","Spanish")),
		array("SetName" => "Ninth Edition", "Frame" =>  "8th","Border" => "White","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Ravnica: City of Guilds", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Guildpact",	 "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Dissension", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Coldsnap",	 "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Time Spiral", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Time Spiral \"Timeshifted\"", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Planar Chaos", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Future Sight", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Tenth Edition", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Lorwyn",	 "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Morningtide", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Eventide",	 "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Shadowmoor", "Frame" => "8th", "Border" => "Black","Foil" => "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Shards of Alara",	"Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Conflux",	 "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Japanese")),
		array("SetName" => "Alara Reborn", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Magic 2010", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Zendikar",	 "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Worldwake",	 "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Rise of the Eldrazi","Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Japanese")),
		array("SetName" => "Archenemy",	 "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Magic 2011", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Scars of Mirrodin",	"Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Japanese")),
		array("SetName" => "Mirrodin Besieged",	"Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "New Phyrexia", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Japanese")),
		array("SetName" => "Commander (2011)", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Magic 2012", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "French", "German", "Italian", "Japanese","Spanish")),
		array("SetName" => "Innistrad",	 "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Japanese")),
		array("SetName" => "Dark Ascension",	"Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Avacyn Restored",	"Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Japanese")),
		array("SetName" => "Magic 2013", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "French", "German", "Italian", "Japanese","Spanish")),
		array("SetName" => "Return to Ravnica",	"Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Japanese")),
		array("SetName" => "Commander's Arsenal","Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Gatecrash",	 "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Dragon's Maze", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Japanese")),
		array("SetName" => "Modern Masters",	"Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Magic 2014 Core Set","Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Theros",	 "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Japanese")),
		array("SetName" => "Commander 2013 Edition", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Born of the Gods",	"Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "French", "German", "Italian", "Japanese","Spanish")),
		array("SetName" => "Journey into Nyx",	"Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Japanese")),
		array("SetName" => "Modern Event Deck",	"Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Magic: The Gathering—Conspiracy", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Magic 2015 Core Set","Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Khans of Tarkir",	"Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Japanese")),
		array("SetName" => "Commander 2014",	"Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Fate Reforged", "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian", "Spanish")),
		array("SetName" => "Dragons of Tarkir",	"Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Japanese")),
		array("SetName" => "Modern Masters 2015 Edition", "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Magic Origins", "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Japanese")),
		array("SetName" => "Battle for Zendikar","Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Japanese")),
		array("SetName" => "Zendikar Expeditions","Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Commander 2015",	"Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Oath of the Gatewatch", "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "French", "German", "Italian", "Japanese","Spanish")),
		array("SetName" => "Shadows over Innistrad", "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Japanese")),
		array("SetName" => "Eternal Masters",	"Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Eldritch Moon", "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Italian")),
		array("SetName" => "Conspiracy: Take the Crown", "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Kaladesh",	 "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian", "Spanish")),
		array("SetName" => "Commander 2016",	"Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Aether Revolt", "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Amonkhet",	 "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),

		## Premium Deck Series
		array("SetName" => "Premium Deck Series: Fire and Lightning", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Premium Deck Series: Graveborn", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Premium Deck Series: Slivers", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),

		## Duel Decks
		array("SetName" => "Duel Decks Anthology", "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "French", "German", "Italian", "Japanese","Spanish")),
		array("SetName" => "Duel Decks Anthology, Divine vs. Demonic", "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Duel Decks Anthology, Elves vs. Goblins", "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Duel Decks Anthology, Garruk vs. Liliana", "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Duel Decks Anthology, Jace vs. Chandra" , "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Duel Decks: Phyrexia vs. the Coalition" , "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Duel Decks: Ajani vs. Nicol Bolas" , "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Duel Decks: Blessed vs. Cursed" , "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Duel Decks: Divine vs. Demonic" , "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Duel Decks: Elspeth vs. Kiora" , "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Duel Decks: Elspeth vs. Tezzeret" , "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Duel Decks: Elves vs. Goblins" , "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Duel Decks: Garruk vs. Liliana" , "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Duel Decks: Heroes vs. Monsters", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Duel Decks: Izzet vs. Golgari", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Duel Decks: Jace vs. Chandra" , "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Duel Decks: Jace vs. Vraska", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Duel Decks: Knights vs. Dragons", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Duel Decks: Nissa vs. Ob Nixilis", "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Japanese")),
		array("SetName" => "Duel Decks: Sorin vs. Tibalt", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Duel Decks: Speed vs. Cunning", "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Duel Decks: Venser vs. Koth", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),
		array("SetName" => "Duel Decks: Zendikar vs. Eldrazi", "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English")),
		
		## From the Vault
		array("SetName" => "From the Vault: Angels", "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),
		array("SetName" => "From the Vault: Annihilation (2014)", "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),
		array("SetName" => "From the Vault: Dragons", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "From the Vault: Exiled", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "From the Vault: Legends", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),
		array("SetName" => "From the Vault: Lore", "Frame" =>  "2015","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),
		array("SetName" => "From the Vault: Realms", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),
		array("SetName" => "From the Vault: Relics", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Portuguese", "Russian","Spanish")),
		array("SetName" => "From the Vault: Twenty", "Frame" =>  "8th","Border" => "Black","Foil" =>  "Yes","Languages" => array("English", "Chinese Simplified", "Chinese Traditional", "French", "German", "Italian", "Japanese", "Korean", "Portuguese", "Russian","Spanish")),
		## Land Sets

		## Unsets
		array("SetName" => "Unhinged", "Frame" =>  "8th","Border" => "Silver","Foil" =>  "Yes","Languages" => array("English")),
		array("SetName" => "Unglued", "Frame" =>  "Original","Border" => "Silver","Foil" =>  "No","Languages" => array("English")),

		## Weird sets! 
		array("SetName" => "Dragon Con", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Media Inserts", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Legend Membership", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Rivals Quick Start Set", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Arena League", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Celebration", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Multiverse Gift Box", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Introductory Two-Player Set", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Portal Demo Game", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Prerelease Events", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Judge Gift Program", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Asia Pacific Land Program", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Guru", "Frame" =>  "Original","Foil" =>  "No","Border" => "Black","Languages" => array("English")),
		array("SetName" => "Wizards of the Coast Online Store", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Battle Royale Box Set", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Super Series", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Friday Night Magic", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "European Land Program", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Magic Player Rewards", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Release Events", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Two-Headed Giant Tournament", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Gateway", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Champs and States", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Coldsnap Theme Decks", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Happy Holidays", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Pro Tour", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Grand Prix", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Worlds", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Magic Game Day", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Launch Parties", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "15th Anniversary", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Summer of Magic", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Wizards Play Network", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Duels of the Planeswalkers", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "World Magic Cup Qualifiers", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Modern Event Deck 2014", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Clash Pack", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Ugin's Fate promos", "Frame" =>  "Original","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Magic: The Gathering-Commander", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Welcome Deck 2016", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Masterpiece Series: Kaladesh Inventions", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Modern Masters 2017 Edition", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Duel Decks: Mind vs. Might", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")),
		array("SetName" => "Masterpiece Series: Amonkhet Invocations", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English")));

$jsonData = file_get_contents('../AllSets.json', true);
$json = json_decode($jsonData, true);


#$testArray = "SetName" => "Limited Edition Alpha", "Frame" =>  "Original","Border" => "Black","Foil" =>  "No","Languages" => array("English"));
$len = count($Data);
for($x=0;$x<$len;$x++){
	$set = $Data[$x]['SetName'];
	foreach($json as $key => $value){
		
		if($set  == $value['name']){
		 	#echo "Match";
			$shortSet =  $value["code"];
			$Data[$x]["ShortName"] = $shortSet;
		} else {} 
	}
}

$Data = json_encode($Data);

$myfile = fopen("SetData.json", "w") or die("Unable to open file!");
fwrite($myfile, $Data);
fclose($myfile);
echo "completed";
?>